added advanced plan validation
TheWeatherCompany/terraform-provider-ibm pull request #2
Opened 2021-03-24 20:05 UTC by wderezin

2021-03-24 20:23 UTC, wderezin commented on ibm/resource_ibm_database.go
> -		),
Moved into new CustomDiff func.

2021-03-25 13:21 UTC, allen-servedio requested changes

2021-03-25 13:21 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +		return fmt.Errorf("%s can not change value after create", name)
```suggestion
		return fmt.Errorf("%s cannot change value after create", name)
```

2021-03-25 13:21 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +		return fmt.Errorf("%s can not scale down from %d to %d", name, old, new)
```suggestion
		return fmt.Errorf("%s cannot scale down from %d to %d", name, old, new)
```

2021-03-30 22:13 UTC, allen-servedio requested changes

2021-03-30 22:13 UTC, allen-servedio commented on go.mod
> +replace github.com/IBM-Cloud/bluemix-go  => ./../bluemix-go
Just checking - is this supposed to be here?

2021-03-30 22:13 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +		dbType = service[len("databases-for-"):]
So if this is not prefixed with "databases-for-" and has a shorter length, this will be an index out of bounds right? Maybe it would make sense to have a friendlier failure if that happens?

2021-03-30 22:13 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +		var divider = groupDefaults.Groups[0].Members.MinimumCount
You may want to explain why this is the right value. It is not clear why this is the divider.

2021-03-30 22:13 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +	// TODO WALT Handle rabbitMQ case without defaults
Is this for the future?

2021-03-30 22:13 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +	//}
What is happening here?

2021-03-30 22:13 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +		return fmt.Errorf("%s can not change value after create", name)
So, not going to apply?

2021-03-30 22:13 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +		return fmt.Errorf("%s can not scale down from %d to %d", name, old, new)
So, not going to apply?

2021-03-30 22:13 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +				ConflictsWith: []string{"node_count", "node_memory_allocation_mb", "node_disk_allocation_mb", "node_cpu_allocation_count"},
So there is lots of repeating code in here. Is there a way that we can do something like factor these things out and reference them (or, like for the code below) us functions?

2021-03-30 22:13 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +		}
Another example - I could see these being folded down to a function where all you have to pass in is `"members_memory_allocation_mb"` and `groupDefaults.Groups[0].Memory` OR `"members_disk_allocation_mb"` and `groupDefaults.Groups[0].Disk`. Similar kinds of reductions could be done for other repeated code.

2021-04-09 15:59 UTC, allen-servedio requested changes

2021-04-09 15:59 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +	return &groupDefaults.Groups[0], nil
Can this be empty and  - if so - won't we get an index out of bounds issue?

2021-04-09 15:59 UTC, allen-servedio commented on ibm/resource_ibm_database.go
> +	//task, err := icdClient.Groups().UpdateGroup(icdId, "member", params)
Can we delete the commented out code here and below?

2021-04-09 18:53 UTC, allen-servedio approved these changes

2021-04-09 18:54 UTC, wderezin commented on ibm/resource_ibm_database.go
> +		dbType = service[len("databases-for-"):]
It's  Go's advanced  range syntax.

2021-04-16 12:49 UTC, allen-servedio commented on ibm/resource_ibm_database_elasticsearch_test.go
> +        node_cpu_allocation_count    = 3
Defined twice?

2024-07-12 11:36 UTC, wderezin commented
To old, closing

2024-07-12 11:36 UTC, closed without merging